name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["10", "12", "13"]
    name: Test Node V${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: |
          yarn
          yarn build
          yarn test
